packages:
  - packages/*
  - internal/*

catalog:
  '@arethetypeswrong/cli': 0.18.2
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  eslint: ^10.0.0
  publint: 0.3.16
  rimraf: ^6.1.2
  typescript: 5.9.3
  vitest: ^4.0.15
  'typedoc': '^0.28.15'
  '@microsoft/api-extractor': ^7.55.2
  '@opentelemetry/api': 1.9.0
  supertest: 7.2.2
  '@types/supertest': 6.0.3
  '@opentelemetry/sdk-trace-node': 2.4.0
  '@opentelemetry/sdk-trace-base': 2.4.0
  '@types/node': 24.10.9
