packages:
  - packages/*
  - internal/*

allowBuilds:
  '@scarf/scarf': false
  cpu-features: true
  esbuild: false
  protobufjs: true
  ssh2: true
  unrs-resolver: true

catalog:
  '@arethetypeswrong/cli': 0.18.5
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  '@microsoft/api-extractor': ^7.55.2
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/sdk-trace-base': 2.4.0
  '@opentelemetry/sdk-trace-node': 2.4.0
  '@types/node': 24.13.3
  '@types/supertest': 7.2.0
  eslint: ^10.4.1
  publint: 0.3.21
  rimraf: ^6.1.2
  supertest: 7.2.2
  typedoc: ^0.28.15
  typescript: 5.9.3
  vitest: ^4.0.15
