packages:
  - packages/*
  - internal/*

catalog:
  '@arethetypeswrong/cli': 0.18.1
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  eslint: ^9.39.1
  publint: 0.3.16
  rimraf: ^6.1.2
  typescript: 5.9.3
  vitest: ^4.0.15
  'typedoc': '^0.28.15'
  '@microsoft/api-extractor': ^7.55.2
