name: init-pnpm
description: 'Initialize the repo with pnpm and install all the dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: 24.x
runs:
  using: composite
  steps:
    - name: Cache turbo build
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
    - name: Set up pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Install TS Project dependencies
      shell: bash
      run: pnpm install
    - name: build
      shell: bash
      run: pnpm run build
