/* eslint-disable */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/** WithRequired type helpers */
type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export interface paths {
  '/simple-request': {
    get: operations['simpleRequest'];
  };
  '/request-with-required-query-parameters': {
    get: operations['requestWithRequiredQueryParameters'];
  };
  '/request-with-optional-query-parameters': {
    post: operations['requestWithOptionalQueryParameters'];
  };
  '/request-with-mixed-query-parameters': {
    get: operations['requestWithMixedQueryParameters'];
  };
  '/request-with-path-parameters/{name}': {
    get: operations['requestWithPathParameters'];
  };
  '/request-with-empty-response': {
    get: operations['requestWithEmptyResponse'];
  };
  '/request-with-headers': {
    get: operations['requestWithHeaders'];
  };
  '/request-with-all/{name}': {
    post: operations['requestWithAll'];
  };
  '/post-request': {
    post: operations['postRequest'];
  };
  '/endpoint-with-multiple-methods': {
    get: operations['endpointWithMultipleMethodsGet'];
    post: operations['endpointWithMultipleMethodsPost'];
    parameters: {
      query?: {
        test?: string;
      };
    };
  };
  '/multiple-status-codes': {
    get: operations['multipleStatusCodes'];
  };
  '/with-5xx-response': {
    get: operations['with5xxResponse'];
  };
  '/optional-request-body': {
    post: operations['optionalRequestBody'];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  simpleRequest: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  requestWithRequiredQueryParameters: {
    parameters: {
      query: {
        name: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  requestWithOptionalQueryParameters: {
    parameters: {
      query?: {
        name?: string;
      };
    };
    requestBody?: {
      content: {
        'application/json': {
          propertyName?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  requestWithMixedQueryParameters: {
    parameters: {
      query: {
        name: string;
        age?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  requestWithPathParameters: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  requestWithEmptyResponse: {
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
  requestWithHeaders: {
    parameters: {
      header: {
        name: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  requestWithAll: {
    parameters: {
      query: {
        first: string;
      };
      header: {
        second: number;
      };
      path: {
        name: string;
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  postRequest: {
    requestBody: {
      content: {
        'application/json': {
          message?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  endpointWithMultipleMethodsGet: {
    parameters: {
      query?: {
        test?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  endpointWithMultipleMethodsPost: {
    parameters: {
      query?: {
        test?: string;
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  multipleStatusCodes: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
            /** @example 42 */
            number?: number;
          };
        };
      };
      /** @description Created */
      201: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
            /** @example test */
            type?: string;
          };
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  with5xxResponse: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
      /** @description Internal Server Error */
      '5xx': {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
  optionalRequestBody: {
    requestBody?: {
      content: {
        'application/json': {
          message?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          'application/json': {
            /** @example Hello, World! */
            message?: string;
          };
        };
      };
    };
  };
}
