/* eslint-disable */
/**
 * This file was automatically generated by @mapcolonies/semantic-conventions npm package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and release new compiled package to regenerate this file.
 */

/**
 * The number of times this task has been attempted. This is used to track retries in the job management system.
 * @constant
 * @public
 */
export const INFRA_JOBNIK_TASK_ATTEMPTS = 'mapcolonies.infra.jobnik.task.attempts';

/**
 * The status being set (e.g., COMPLETED). For update_status spans
 * @constant
 * @public
 */
export const INFRA_JOBNIK_TASK_STATUS = 'mapcolonies.infra.jobnik.task.status';

/**
 * The status being set (e.g., COMPLETED). For update_status spans
 * @constant
 * @public
 */
export const INFRA_JOBNIK_STAGE_STATUS = 'mapcolonies.infra.jobnik.stage.status';

/**
 * The UUID of the stage.
 * @constant
 * @public
 */
export const INFRA_JOBNIK_STAGE_ID = 'mapcolonies.infra.jobnik.stage.id';

/**
 * The status being set (e.g., COMPLETED). For update_status spans
 * @constant
 * @public
 */
export const INFRA_JOBNIK_JOB_STATUS = 'mapcolonies.infra.jobnik.job.status';

/**
 * The priority of the job (e.g., HIGH)
 * @constant
 * @public
 */
export const INFRA_JOBNIK_JOB_PRIORITY = 'mapcolonies.infra.jobnik.job.priority';

/**
 * The human-readable name of the job
 * @constant
 * @public
 */
export const INFRA_JOBNIK_JOB_NAME = 'mapcolonies.infra.jobnik.job.name';

/**
 * API url of job management service
 * @constant
 * @public
 */
export const INFRA_JOB_MANAGEMENT_SERVICE_URL = 'mapcolonies.infra.job_management.service_url';

/**
 * Type of task as stored on db (uuid)
 * @constant
 * @public
 */
export const INFRA_JOB_MANAGEMENT_TASK_TYPE = 'mapcolonies.infra.job_management.task_type';

/**
 * Type of job as stored on db (uuid)
 * @constant
 * @public
 */
export const INFRA_JOB_MANAGEMENT_JOB_TYPE = 'mapcolonies.infra.job_management.job_type';

/**
 * Type of task as stored on db (uuid)
 * @constant
 * @public
 */
export const INFRA_JOB_MANAGEMENT_TASK_ID = 'mapcolonies.infra.job_management.task_id';

/**
 * Type of task as stored on db (uuid)
 * @constant
 * @public
 */
export const INFRA_JOB_MANAGEMENT_JOB_ID = 'mapcolonies.infra.job_management.job_id';

/**
 * name of the domain in use
 * @constant
 * @public
 */
export const INFRA_CONVENTIONS = {
  infra: {
    jobnik: {
      task: {
        /**
         * The number of times this task has been attempted. This is used to track retries in the job management system.
         * @constant
         * @public
         */
        attempts: 'mapcolonies.infra.jobnik.task.attempts',
        /**
         * The status being set (e.g., COMPLETED). For update_status spans
         * @constant
         * @public
         */
        status: 'mapcolonies.infra.jobnik.task.status',
      },
      stage: {
        /**
         * The status being set (e.g., COMPLETED). For update_status spans
         * @constant
         * @public
         */
        status: 'mapcolonies.infra.jobnik.stage.status',
        /**
         * The UUID of the stage.
         * @constant
         * @public
         */
        id: 'mapcolonies.infra.jobnik.stage.id',
      },
      job: {
        /**
         * The status being set (e.g., COMPLETED). For update_status spans
         * @constant
         * @public
         */
        status: 'mapcolonies.infra.jobnik.job.status',
        /**
         * The priority of the job (e.g., HIGH)
         * @constant
         * @public
         */
        priority: 'mapcolonies.infra.jobnik.job.priority',
        /**
         * The human-readable name of the job
         * @constant
         * @public
         */
        name: 'mapcolonies.infra.jobnik.job.name',
      },
    },
    jobManagement: {
      /**
       * API url of job management service
       * @constant
       * @public
       */
      serviceUrl: 'mapcolonies.infra.job_management.service_url',
      /**
       * Type of task as stored on db (uuid)
       * @constant
       * @public
       */
      taskType: 'mapcolonies.infra.job_management.task_type',
      /**
       * Type of job as stored on db (uuid)
       * @constant
       * @public
       */
      jobType: 'mapcolonies.infra.job_management.job_type',
      /**
       * Type of task as stored on db (uuid)
       * @constant
       * @public
       */
      taskId: 'mapcolonies.infra.job_management.task_id',
      /**
       * Type of task as stored on db (uuid)
       * @constant
       * @public
       */
      jobId: 'mapcolonies.infra.job_management.job_id',
    },
  },
} as const;
