/* eslint-disable */
/**
 * This file was automatically generated by @mapcolonies/semantic-conventions npm package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and release new compiled package to regenerate this file.
 */

/**
 * This represent the location of mapproxy yaml configuration file
 * @constant
 * @public
 */
export const RASTER_MAPPROXY_API_MAPPROXY_YAML_PATH = 'mapcolonies.raster.mapproxy_api.mapproxy_yaml_path';

/**
 * This represent the layer cache name stored in mapproxy config
 * @constant
 * @public
 */
export const RASTER_MAPPROXY_API_CACHE_NAME = 'mapcolonies.raster.mapproxy_api.cache_name';

/**
 * Path of seed.yaml
 * @constant
 * @public
 */
export const RASTER_CACHE_SEEDER_SEED_YAML_PATH = 'mapcolonies.raster.cache_seeder.seed_yaml_path';

/**
 * Time factor to running mapproxy-seed
 * @constant
 * @public
 */
export const RASTER_CACHE_SEEDER_REFRESH_BEFORE = 'mapcolonies.raster.cache_seeder.refresh_before';

/**
 * Grids for seeding process
 * @constant
 * @public
 */
export const RASTER_CACHE_SEEDER_GRIDS = 'mapcolonies.raster.cache_seeder.grids';

/**
 * Mapproxy seed mode - seed or clean tiles
 * @constant
 * @public
 */
export const RASTER_CACHE_SEEDER_SEED_MODE = 'mapcolonies.raster.cache_seeder.seed_mode';

/**
 * layer Id as stored on raster catalog db
 * @constant
 * @public
 */
export const RASTER_CATALOG_MANAGER_CATALOG_ID = 'mapcolonies.raster.catalog_manager.catalog_id';

/**
 * name of the domain in use
 * @constant
 * @public
 */
export const RASTER_CONVENTIONS = {
  raster: {
    mapproxyApi: {
      /**
       * This represent the location of mapproxy yaml configuration file
       * @constant
       * @public
       */
      mapproxyYamlPath: 'mapcolonies.raster.mapproxy_api.mapproxy_yaml_path',
      /**
       * This represent the layer cache name stored in mapproxy config
       * @constant
       * @public
       */
      cacheName: 'mapcolonies.raster.mapproxy_api.cache_name',
    },
    cacheSeeder: {
      /**
       * Path of seed.yaml
       * @constant
       * @public
       */
      seedYamlPath: 'mapcolonies.raster.cache_seeder.seed_yaml_path',
      /**
       * Time factor to running mapproxy-seed
       * @constant
       * @public
       */
      refreshBefore: 'mapcolonies.raster.cache_seeder.refresh_before',
      /**
       * Grids for seeding process
       * @constant
       * @public
       */
      grids: 'mapcolonies.raster.cache_seeder.grids',
      /**
       * Mapproxy seed mode - seed or clean tiles
       * @constant
       * @public
       */
      seedMode: 'mapcolonies.raster.cache_seeder.seed_mode',
    },
    catalogManager: {
      /**
       * layer Id as stored on raster catalog db
       * @constant
       * @public
       */
      catalogId: 'mapcolonies.raster.catalog_manager.catalog_id',
    },
  },
} as const;
