/* eslint-disable */
/**
 * This file was automatically generated by @mapcolonies/semantic-conventions npm package.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and release new compiled package to regenerate this file.
 */

/**
 * Model ID as stored on 3D catalog DB
 * @constant
 * @public
 */
export const THREE_D_CATALOG_MANAGER_CATALOG_ID = 'mapcolonies.3d.catalog_manager.catalog_id';

/**
 * Name of the domain in use
 * @constant
 * @public
 */
export const THREE_D_CONVENTIONS = {
  three_d: {
    catalogManager: {
      /**
       * Model ID as stored on 3D catalog DB
       * @constant
       * @public
       */
      catalogId: 'mapcolonies.3d.catalog_manager.catalog_id',
    },
  },
} as const;
